"""Encoding, the size ladder, and provenance metadata.

Every avatar is written at several sizes so a web app can drop in the right
one without a resize step, and every file carries metadata saying it was
machine-generated, by what, and from which seed. That last part is cheap to do
and makes the images honest and traceable; there is no good reason to ship
synthetic faces without it.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from PIL import Image
from PIL.PngImagePlugin import PngInfo

# EXIF tag numbers (Pillow exposes these as plain ints).
_EXIF_IMAGE_DESCRIPTION = 0x010E
_EXIF_SOFTWARE = 0x0131
_EXIF_ARTIST = 0x013B
_EXIF_COPYRIGHT = 0x8298

SOFTWARE_TAG = "profile-photo-generator"
PROVENANCE_NOTE = "Synthetic image. Generated by a diffusion model. Depicts no real person."


def build_metadata(
    *,
    model: str,
    backend: str,
    seed: int,
    prompt: str,
    negative_prompt: str,
    attributes: dict[str, Any],
    persona: dict[str, Any] | None,
    version: str,
) -> dict[str, str]:
    """The provenance record embedded in every output file."""
    return {
        "Software": f"{SOFTWARE_TAG} {version}",
        "AIGenerated": "true",
        "Description": PROVENANCE_NOTE,
        "Model": model,
        "Backend": backend,
        "Seed": str(seed),
        "Prompt": prompt,
        "NegativePrompt": negative_prompt,
        "Attributes": json.dumps(attributes, sort_keys=True, ensure_ascii=False),
        "Persona": json.dumps(persona or {}, sort_keys=True, ensure_ascii=False),
    }


def _png_info(metadata: dict[str, str]) -> PngInfo:
    info = PngInfo()
    for key, value in metadata.items():
        info.add_text(key, value)
    return info


def _exif_bytes(metadata: dict[str, str]) -> bytes:
    """Pack provenance into EXIF for formats without PNG text chunks.

    EXIF has no free-form key/value store, so the full record goes into
    ImageDescription as JSON and the human-readable bits get proper tags.
    """
    exif = Image.Exif()
    exif[_EXIF_SOFTWARE] = metadata.get("Software", SOFTWARE_TAG)
    exif[_EXIF_ARTIST] = SOFTWARE_TAG
    exif[_EXIF_COPYRIGHT] = PROVENANCE_NOTE
    exif[_EXIF_IMAGE_DESCRIPTION] = json.dumps(metadata, sort_keys=True, ensure_ascii=False)
    return exif.tobytes()


def to_square(image: Image.Image) -> Image.Image:
    """Centre-crop to a square. Avatars are square almost everywhere."""
    width, height = image.size
    if width == height:
        return image
    side = min(width, height)
    left = (width - side) // 2
    # Bias the crop upwards: on a portrait, the face sits above centre.
    top = int((height - side) * 0.35)
    return image.crop((left, top, left + side, top + side))


def write_variants(
    image: Image.Image,
    dest_dir: Path,
    sizes: list[int],
    metadata: dict[str, str],
    *,
    webp_quality: int = 90,
) -> dict[str, str]:
    """Write every size in both formats. Returns ``{"1024.webp": "...", ...}``.

    The largest size is saved from the original render; the rest are
    downscaled with LANCZOS, which keeps skin texture and eyelashes crisp
    where a bilinear resize turns them to mush.
    """
    dest_dir.mkdir(parents=True, exist_ok=True)
    square = to_square(image.convert("RGB"))
    written: dict[str, str] = {}

    png_info = _png_info(metadata)
    exif = _exif_bytes(metadata)

    for size in sorted(set(sizes), reverse=True):
        resized = (
            square
            if square.size[0] == size
            else square.resize((size, size), Image.Resampling.LANCZOS)
        )

        png_path = dest_dir / f"{size}.png"
        resized.save(png_path, "PNG", pnginfo=png_info, optimize=True)
        written[f"{size}.png"] = png_path.name

        webp_path = dest_dir / f"{size}.webp"
        resized.save(webp_path, "WEBP", quality=webp_quality, method=6, exif=exif)
        written[f"{size}.webp"] = webp_path.name

    return written


def read_metadata(path: Path) -> dict[str, str]:
    """Read provenance back out of a written file. Used by the tests and CLI."""
    with Image.open(path) as image:
        if image.format == "PNG":
            return dict(image.text)  # type: ignore[attr-defined]
        exif = image.getexif()
        raw = exif.get(_EXIF_IMAGE_DESCRIPTION)
        if not raw:
            return {}
        try:
            data = json.loads(raw)
        except (json.JSONDecodeError, TypeError):
            return {}
        return data if isinstance(data, dict) else {}
